In [3]:
import pandas as pd
import numpy as np

In [4]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

#### Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.

In [5]:
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [6]:
big_secret[::2, ::2] = 1

In [7]:
big_secret

array([[1.00000000e+00, 1.00000000e+01, 1.00000000e+00, 5.60000000e+01,
        1.00000000e+00, 2.40000000e+01, 1.00000000e+00, 7.00000000e+01,
        1.00000000e+00, 1.40000000e+02, 1.00000000e+00, 6.00000000e+01,
        1.00000000e+00, 1.30000000e+02, 1.00000000e+00, 2.24000000e+02,
        1.00000000e+00, 9.60000000e+01, 1.00000000e+00, 1.90000000e+02,
        1.00000000e+00, 3.08000000e+02, 1.00000000e+00, 1.32000000e+02,
        1.00000000e+00, 2.50000000e+02, 1.00000000e+00, 3.92000000e+02,
        1.00000000e+00, 1.68000000e+02, 1.00000000e+00, 3.10000000e+02,
        1.00000000e+00, 4.76000000e+02, 1.00000000e+00, 2.04000000e+02,
        1.00000000e+00, 3.70000000e+02, 1.00000000e+00, 5.60000000e+02,
        1.00000000e+00, 2.40000000e+02, 1.00000000e+00, 4.30000000e+02,
        1.00000000e+00, 6.44000000e+02, 1.00000000e+00, 2.76000000e+02,
        1.00000000e+00, 4.90000000e+02, 1.00000000e+00],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [8]:
big_secret[1::2, 1::2] = -1

In [9]:
big_secret

array([[ 1.00000000e+00,  1.00000000e+01,  1.00000000e+00,
         5.60000000e+01,  1.00000000e+00,  2.40000000e+01,
         1.00000000e+00,  7.00000000e+01,  1.00000000e+00,
         1.40000000e+02,  1.00000000e+00,  6.00000000e+01,
         1.00000000e+00,  1.30000000e+02,  1.00000000e+00,
         2.24000000e+02,  1.00000000e+00,  9.60000000e+01,
         1.00000000e+00,  1.90000000e+02,  1.00000000e+00,
         3.08000000e+02,  1.00000000e+00,  1.32000000e+02,
         1.00000000e+00,  2.50000000e+02,  1.00000000e+00,
         3.92000000e+02,  1.00000000e+00,  1.68000000e+02,
         1.00000000e+00,  3.10000000e+02,  1.00000000e+00,
         4.76000000e+02,  1.00000000e+00,  2.04000000e+02,
         1.00000000e+00,  3.70000000e+02,  1.00000000e+00,
         5.60000000e+02,  1.00000000e+00,  2.40000000e+02,
         1.00000000e+00,  4.30000000e+02,  1.00000000e+00,
         6.44000000e+02,  1.00000000e+00,  2.76000000e+02,
         1.00000000e+00,  4.90000000e+02,  1.00000000e+0

In [54]:
a = []
for i in big_secret:
    for j in i[:5]:
        a.append(j)
        

In [55]:
a

[1.0,
 10.0,
 1.0,
 56.0,
 1.0,
 31.622776601683793,
 -1.0,
 31.68595903550972,
 -1.0,
 31.74901573277509,
 1.0,
 1.0,
 1.0,
 9.0,
 1.0,
 31.622776601683793,
 -1.0,
 31.68595903550972,
 -1.0,
 31.74901573277509,
 1.0,
 10.0,
 1.0,
 56.0,
 1.0]

In [56]:
a1 = a[:5]

In [57]:
a1

[1.0, 10.0, 1.0, 56.0, 1.0]

In [17]:
newarr = big_secret[:, -5:]

In [18]:
newarr

array([[ 1.00000000e+00,  2.76000000e+02,  1.00000000e+00,
         4.90000000e+02,  1.00000000e+00],
       [ 3.30454233e+01, -1.00000000e+00,  3.31058907e+01,
        -1.00000000e+00,  3.31662479e+01],
       [ 1.00000000e+00,  2.20900000e+03,  1.00000000e+00,
         2.40100000e+03,  1.00000000e+00],
       [ 3.30454233e+01, -1.00000000e+00,  3.31058907e+01,
        -1.00000000e+00,  3.31662479e+01],
       [ 1.00000000e+00,  2.76000000e+02,  1.00000000e+00,
         4.90000000e+02,  1.00000000e+00]])

In [20]:
1.00000000e+00 * (-1.00000000e+00) * 1.00000000e+00 * (-1.00000000e+00) * 1.00000000e+00

1.0

In [23]:
p = 0
m = 1
for i in newarr:
    m*=i[p]
    p+=1
m   

1.0

In [24]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))


Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [25]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [32]:
my_array = np.random.randint(0, 10, (3,4))

In [33]:
my_array

array([[6, 3, 0, 7],
       [0, 6, 4, 8],
       [8, 5, 9, 6]])

In [35]:
my_array[my_array<5]

array([3, 0, 0, 4])

In [37]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[6, 0],
       [0, 4],
       [8, 9]])

In [41]:
my_array = np.random.randint(0, 10, (4, 6))

print(my_array)
print(np.sort(my_array, axis=0))

[[3 7 5 4 1 4]
 [6 9 8 7 6 4]
 [4 3 4 1 5 3]
 [4 7 1 2 8 4]]
[[3 3 1 1 1 3]
 [4 7 4 2 5 4]
 [4 7 5 4 6 4]
 [6 9 8 7 8 4]]


In [42]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [45]:
great_secret.shape

(100, 3)

In [58]:
import math
p = 0
for i in great_secret[0]:
#     print(math.cos(i))
    p += math.cos(i)
p

0.16006721889793019

In [48]:
great_secret[0]

array([ 0.        ,  4.64158883, 66.66666667])

In [60]:
great_secret.flatten()[150]

7.0710678118654755

In [61]:
great_secret[great_secret>50].sum()

5470.0

In [67]:
newarr = np.sort(great_secret, axis = 0) 

In [68]:
newarr[-1].sum()

115.12148016521353

In [69]:
head = ['id', 'height', 'weight', 'gpa']

In [73]:
col1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [74]:
col2 = [135, 160, 163, 147, 138, 149, 136, 154, 137, 165]

In [75]:
col3 = [34, 43, 40, 44, 41, 54, 39, 48, 35, 60]

In [76]:
col4 = [4, 5, 4.3, 5, 4.7, 3.9, 4.2, 4.9, 3.7, 4.6]

In [84]:
table = np.array([col1, col2, col3, col4])

In [82]:
tablet = np.array([head, table.T])

In [89]:
students = table.T

In [90]:
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [91]:
mean = np.mean(students[:,-1])
mean


4.430000000000001

In [93]:
median = np.median(students[:,-2])
median

42.0

In [94]:
np.mean(students[:,-2]) - np.median(students[:,-2])

1.7999999999999972

In [95]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [96]:
corr = np.corrcoef(students[:,1], students[:,3])
corr

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

In [97]:
corr = np.corrcoef(students[:,2], students[:,3])
corr

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [101]:
std = np.std(students[:,2])
std ** 2


60.36

In [103]:
np.ones((5,10), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [104]:
np.full((10, 5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [106]:
np.array([x/x for x in range(1,10)]*5)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [107]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [117]:
my_array[1:4, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

### Создайте массив bigdata, содержащий квадраты всех нечётных чисел в диапазоне от 100 до 1000.

In [ ]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [126]:
mass = [x**2 for x in range(101, 1000, 2)]

In [127]:
bigdata = np.array([mass])

In [130]:
np.std(bigdata)

292095.0301991155